export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS"

export const REGISTRATION_SUCCESS = "AUTH/REGISTRATION_SUCCESS"

export const CHANGE_PASSWORD_SUCCESS = "AUTH/CHANGE_PASSWORD_SUCCESS"

export const SET_ERROR = "AUTH/SET_ERROR"
export const SET_SERVER_MESS = "AUTH/SET_SERVER_MESS"



export const REG_STATE = "INPUT/REG_STATE"
export const LOGIN_STATE = "INPUT/LOGIN_STATE"
export const CHANGE_PASSWORD_STATE = "INPUT/CHANGE_PASSWORD_STATE"